### ISSUE TITLE
Broken URLs at the bottom of readme.md

### ISSUE THREAD

**Issue by dragon-dxw** [dawnwages/LCARS-on-Wagtail#2]
The URLs to the website and blog need to be fully specified (i.e. start with https:// ) otherwise markdown assumes they're relative to the `readme.md`

```
My website: [dawnwages.info](dawnwages.info)
Blog: [glittertech.dev](glittertech.dev)
```

Also, I wanted to say I love what you've done with LCARS :)

**Comment by dawnwages** [comment]
Thanks for letting me know! :) I'm excited at the prospects.
